fix(modules/kms_secrets): use custom kms for ssm params
RSS-Engineering/terraform pull request #21
Opened 2022-12-05 16:56 UTC by thinhdev1

# Descriptions
- Update documentation to move `secretsmanager_key` and `ssm_parameter_prefix` as top level variables.
- Fix bug that uses default aws managed ssm key.

2022-12-05 19:31 UTC, smayberry commented on modules/kms_secrets/variables.tf
> +  description = "Use the default AWS managed KMS key to encrypt the secrets in SSM Parameter Store"
This description seems reversed.

2022-12-05 21:24 UTC, szilveszter approved these changes
Thank you for calling out this issue and for the documentation fix!

2022-12-06 22:00 UTC, explorigin requested changes
I have good news and bad news:
- The bad news is that `data.aws_kms_alias.aws_ssm` is a static reference to a specific kms key. We can't put static references like that in shared libraries.
- The good news is that I don't think any of these changes are necessary to achieve what you want. The critical line is main.tf:48. In that, you're providing a target_key_id from the data resource. But the previous implementation has it passed into the module adjacent to the ciphertext. Just pass what you want there.

2022-12-08 13:00 UTC, thinhdev1 commented
@explorigin I discussed with @szilveszter before submitting this PR about the default AWS managed KMS key. If we don't use it, this PR will be not backward compatibility.  Are y'all ok with that?

2022-12-08 14:03 UTC, explorigin commented
> @explorigin I discussed with @szilveszter before submitting this PR about the default AWS managed KMS key. If we don't use it, this PR will be not backward compatibility. Are y'all ok with that?

We should probably have a zoom talk about this. I have more questions. Send me a meeting invitation.

2022-12-09 18:23 UTC, explorigin commented
After talking about this, I understand why this is. The only concern left that I have is potentially breaking existing projects because of the added data directive. @thinhdev1 will recreate this PR with a branch off this repo so I can test in one of my staging environments. If it's not broken, this will be good to merge.

2022-12-09 18:25 UTC, closed without merging